"use client";

import { useEffect, useState } from "react";
import { CONTRACT_ADDRESS, CONTRACT_READY, friendlyError, formatDuration, getAdminData, NETWORK_NAME } from "@/lib/contract";

export default function AdminDashboard() {
  const [data, setData] = useState<{ config: Record<string, string>; stats: Record<string, string> } | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (CONTRACT_READY) void getAdminData().then(setData).catch((e) => setError(friendlyError(e))); }, []);
  return <main className="admin-page"><nav className="nav shell"><a href="/" className="brand"><span className="brand-mark">BF</span><span>Bounty<span className="accent">Forge</span></span></a><a className="button ghost small" href="/">← Back to app</a></nav><section className="admin shell"><p className="eyebrow">READ-ONLY PROTOCOL CONSOLE</p><h1>Trust, in the open.</h1><p className="lede">A transparent view of the deployed BountyForge contract. Outcomes and escrow remain controlled by the contract; this surface cannot rewrite them.</p>{!CONTRACT_READY ? <div className="empty-state"><h3>Deployment not configured</h3><p>Set <code>NEXT_PUBLIC_BOUNTYFORGE_ADDRESS</code> to the recorded {NETWORK_NAME} address before hosting this console.</p></div> : error ? <div className="alert">{error}</div> : !data ? <div className="progress"><span className="spinner" />Reading finalized protocol state…</div> : <><div className="stat-grid">{[["Created", data.stats.total_created], ["Claims", data.stats.total_claims_submitted], ["Accepted", data.stats.total_accepted], ["Settled", data.stats.total_settled]].map(([label, value]) => <div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="admin-grid"><section className="admin-card"><p className="eyebrow">DEPLOYMENT</p><div className="admin-row"><span>Network</span><b>{NETWORK_NAME}</b></div><div className="admin-row"><span>Contract</span><code>{CONTRACT_ADDRESS}</code></div><div className="admin-row"><span>Version</span><b>{data.config.version}</b></div><div className="admin-row"><span>Policy</span><b>{data.config.adjudication_policy}</b></div></section><section className="admin-card"><p className="eyebrow">GUARDRAILS</p><div className="admin-row"><span>Claim stake</span><b>{data.config.claim_stake_atto} atto</b></div><div className="admin-row"><span>Challenge window</span><b>{formatDuration(data.config.challenge_window_secs)}</b></div><div className="admin-row"><span>Appeal window</span><b>{formatDuration(data.config.appeal_window_secs)}</b></div><div className="admin-row"><span>Claim slots</span><b>{data.config.max_claims_per_bounty}</b></div></section></div></>}</section></main>;
}
